### ISSUE TITLE
Unable to create Holograms

### ISSUE THREAD

**Issue by MythicProjectz** [randombyte-developer/holograms#16]
When I try and create a hologram, I get this error
http://prntscr.com/fkx7lj

**Comment by randombyte-developer** [comment]
Which Sponge version are you using and please send me the whole server log. It might be a Sponge bug that was reported to me some time ago.

**Comment by MythicProjectz** [comment]
Here are the server logs and FML logs.


[latest.zip](https://github.com/randombyte-developer/holograms/files/1082663/latest.zip)
[fml-server-latest.zip](https://github.com/randombyte-developer/holograms/files/1082672/fml-server-latest.zip)

**Comment by randombyte-developer** [comment]
First try updating to the latest sponge version, as described [here](https://forums.spongepowered.org/t/holograms-easily-create-floating-texts/12861/247?u=randombyte).

This is the relevant part, I also included a warning regarding another plugin: https://gist.github.com/randombyte-developer/a82e7a820980df987304d6ba1259d031

@gabizou That's the same issue as with Holograms *after* your fix([link to that](https://forums.spongepowered.org/t/holograms-easily-create-floating-texts/12861/250?u=randombyte)). Interestingly the other plugin, here `edifice`, doesn't have the problems my plugins have. What am I doing wrong? Is it due to Kotlin somehow? [That's](https://github.com/EdificeMC/Edifice/blob/086822479092567fff6ea545a4cd0ea613d18d3a/src/main/java/me/reherhold/edifice/Edifice.java#L194) how edifice does it.

Edit: Äh, sorry, I thought this issue was about another plugin. But it is still strange.

**Comment by MythicProjectz** [comment]
Ok so things have changed a bit after I updated to the latest stable SpongeForge for 1.11.2
1.) I can place holograms but an error spits out 
     http://prntscr.com/fkyipi     http://prntscr.com/fkyiz0

2.) Now when I try to delete the hologram, nothing appears for me to do so.
    http://prntscr.com/fkyjll

Here the the logs.
[Logs.zip](https://github.com/randombyte-developer/holograms/files/1082712/Logs.zip)

**Comment by randombyte-developer** [comment]
Yes, that's what other player experience too. The relevant part: https://gist.github.com/randombyte-developer/a830fb624b7ad46b68dc02651a8ee47e
I will create an issue on SpongeCommon regarding this.

**Comment by randombyte-developer** [comment]
Try v2.3, which is for Sponge API v7.
